/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface OPDRecord {
  'age' : bigint,
  'appointmentDate' : string,
  'address' : string,
  'gender' : Gender,
  'patientName' : string,
  'doctorName' : string,
}
export interface PatientProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllOPDRecords' : ActorMethod<[], Array<OPDRecord>>,
  'getAllPatientProfiles' : ActorMethod<[], Array<PatientProfile>>,
  'getCallerPatientProfile' : ActorMethod<[], [] | [PatientProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [PatientProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPatientOPDRecords' : ActorMethod<[Principal], Array<OPDRecord>>,
  'getPatientProfile' : ActorMethod<[Principal], [] | [PatientProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [PatientProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerPatient' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[PatientProfile], undefined>,
  'submitOPDForm' : ActorMethod<
    [string, bigint, string, Gender, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];