/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const OPDRecord = IDL.Record({
  'age' : IDL.Nat,
  'appointmentDate' : IDL.Text,
  'address' : IDL.Text,
  'gender' : Gender,
  'patientName' : IDL.Text,
  'doctorName' : IDL.Text,
});
export const PatientProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllOPDRecords' : IDL.Func([], [IDL.Vec(OPDRecord)], ['query']),
  'getAllPatientProfiles' : IDL.Func([], [IDL.Vec(PatientProfile)], ['query']),
  'getCallerPatientProfile' : IDL.Func(
      [],
      [IDL.Opt(PatientProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PatientProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPatientOPDRecords' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(OPDRecord)],
      ['query'],
    ),
  'getPatientProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PatientProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PatientProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerPatient' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([PatientProfile], [], []),
  'submitOPDForm' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, Gender, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const OPDRecord = IDL.Record({
    'age' : IDL.Nat,
    'appointmentDate' : IDL.Text,
    'address' : IDL.Text,
    'gender' : Gender,
    'patientName' : IDL.Text,
    'doctorName' : IDL.Text,
  });
  const PatientProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllOPDRecords' : IDL.Func([], [IDL.Vec(OPDRecord)], ['query']),
    'getAllPatientProfiles' : IDL.Func(
        [],
        [IDL.Vec(PatientProfile)],
        ['query'],
      ),
    'getCallerPatientProfile' : IDL.Func(
        [],
        [IDL.Opt(PatientProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PatientProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPatientOPDRecords' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(OPDRecord)],
        ['query'],
      ),
    'getPatientProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PatientProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PatientProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerPatient' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([PatientProfile], [], []),
    'submitOPDForm' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, Gender, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };